GET http://localhost:3000/books
###

GET http://localhost:3000/books?genre=Dystopia

###
GET http://localhost:3000/books/2

###
GET http://localhost:3000/books/999

###
GET http://localhost:3000/books/unknown



